language: r
cache: packages
warnings_are_errors: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libssl-dev
      - libxml2-dev

r:
  - release
  - devel

r_packages:
  - devtools
  - testthat
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
